development:
  adapter: redis
  url: redis://:<%= Rails.application.credentials.redis_password %>@localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://:#{Rails.application.credentials.redis_password}@localhost:6379/1" } %>
  channel_prefix: lsa_evaluate_production
