default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "root" } %>
  password: <%= ENV.fetch['LOCAL_MYSQL_DATABASE_PASSWORD'] %>
  port: 3306

development:
  <<: *default
  database: lsa_evaluate_development

development_feature:
  <<: *default
  database: lsa_evaluate_development_feature

test:
  <<: *default
  database: lsa_evaluate_test

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  database: evaluate_db_prod
  username: <%= Rails.application.credentials.mysql[:prod_user] %>
  password: <%= Rails.application.credentials.mysql[:prod_password] %>
  host: <%= Rails.application.credentials.mysql[:prod_servername] %>
  sslca: <%= Rails.application.credentials.mysql[:prod_sslca] %>
