default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: 3306

development:
  <<: *default
  database: lsa_evaluate_development

development_feature:
  <<: *default
  database: lsa_evaluate_development_feature

test:
  <<: *default
  database: lsa_evaluate_test

staging:
  <<: *default
  database: lsa_evaluate_staging

production:
  <<: *default
  # url: <%= ENV["DATABASE_URL"] %>
  database: lsa_evaluate_production
  username: <%= Rails.application.credentials.mysql[:prod_user] %>
  password: <%= Rails.application.credentials.mysql[:prod_password] %>
  host: <%= Rails.application.credentials.mysql[:prod_servername] %>
  sslca: <%= Rails.application.credentials.mysql[:prod_sslca] %>
