---
reason: We are currently doing maintenance on the LSA Evaluate application. <small>(code 241009)</small>
allowed_paths:
allowed_ips:
# UMVPN - All Traffic or UMVPN - Only U-M Traffic range
# - 35.7.0.0/18
- 35.7.37.16
response_code: 503
retry_after: 3600