---
:concurrency: 5
# In Sidekiq 7.3.x, we set retry at the global level
:retry: 3

# Sidekiq will run this file through ERB when loading it
:queues:
  - [critical, 3]
  - [default, 2]
  - [<%= ENV['RAILS_ENV'] || 'development' %>, 2]
  - [<%= ENV['RAILS_ENV'] || 'development' %>_mailers, 2]
  - [low, 1]

development:
  :concurrency: 5
  :retry: 3

test:
  :concurrency: 1
  :retry: 3

staging:
  :concurrency: 10
  :retry: 5

production:
  :concurrency: 20
  :retry: 10
