---
:concurrency: 5
# In Sidekiq 7.x, max_retries is set via default_worker_options
:default_worker_options:
  retry: 3

# Sidekiq will run this file through ERB when loading it
:queues:
  - [critical, 3]
  - [default, 2]
  - [<%= ENV['RAILS_ENV'] || 'development' %>, 2]
  - [<%= ENV['RAILS_ENV'] || 'development' %>_mailers, 2]
  - [low, 1]

development:
  :concurrency: 5
  :default_worker_options:
    retry: 3

test:
  :concurrency: 1
  :default_worker_options:
    retry: 3

staging:
  :concurrency: 10
  :default_worker_options:
    retry: 5

production:
  :concurrency: 20
  :default_worker_options:
    retry: 10
