---
# Default configuration
:concurrency: 5
:retry: 3

# Sidekiq will run this file through ERB when loading it
:queues:
  - [critical, 3]
  - [default, 2]
  - [<%= ENV['RAILS_ENV'] || 'development' %>, 2]
  - [<%= ENV['RAILS_ENV'] || 'development' %>_mailers, 2]
  - [low, 1]

# Environment-specific configurations
development:
  :concurrency: 5

test:
  :concurrency: 1

staging:
  :concurrency: 10
  :retry: 5

production:
  :concurrency: 20
  :retry: 10
