---
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google_production:
  service: GCS
  project: <%= Rails.application.credentials.dig(:google_cloud, :project_id) || "dummy-project" %>
  credentials: <%= Rails.root.join(Rails.application.credentials.dig(:google_cloud, :credentials_file_path) || "dummy-credentials.json") %>
  bucket: <%= Rails.application.credentials.dig(:google_cloud, :bucket) || "dummy-bucket" %>
