---
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: <%= Rails.application.credentials.dig(:google_cloud, :project_id) %>
  credentials: <%= ENV['GCS_KEYFILE_JSON'] %>
  bucket: <%= Rails.application.credentials.dig(:google_cloud, :bucket) %>
