version: "3.8"

services:
  saturn_test_app:
    hostname: saturn_test_app
    build:
      context: ../
      dockerfile: .saturnci/Dockerfile
    image: ${SATURN_TEST_APP_IMAGE_URL}
    volumes:
      - ../:/code
    depends_on:
      - mysql
      - chrome
    # Optionally, you can add a local .saturnci.env file to provide environment
    # variables when you run your SaturnCI setup locally.
    env_file:
      - .env
    environment:
      SATURNCI_ENV: "true"
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ""
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      RAILS_ENV: test

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 10
    logging:
      driver: none

  chrome:
    image: seleniarm/standalone-chromium
    hostname: chrome
    shm_size: 2g
    ports:
      - "4444:4444"
volumes:
  mysql_data:
