name: Brakeman Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

permissions:
  contents: read
  actions: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman -A -q -o tmp/brakeman-report.json

      - name: Upload Brakeman report
        uses: actions/upload-artifact@v3
        with:
          name: brakeman-report
          path: tmp/brakeman-report.json
