name: Brakeman Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.4'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run Brakeman
      run: bundle exec rake brakeman:check
      # If you want to run Brakeman but not fail the build, use:
      # run: bundle exec rake brakeman:run

    - name: Upload Brakeman report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: brakeman-report
        path: |
          tmp/brakeman-report.html
          tmp/brakeman-report.json
